FROM node:20-alpine

ARG TG_BOT_TOKEN
ARG TG_CHAT_ID
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_TG_LINK
ARG NEXT_PUBLIC_GITHUB_LINK
ARG NEXT_PUBLIC_TG_GROUP_LINK

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV TG_BOT_TOKEN=$TG_BOT_TOKEN
ENV TG_CHAT_ID=$TG_CHAT_ID
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_TG_LINK=$NEXT_PUBLIC_TG_LINK
ENV NEXT_PUBLIC_GITHUB_LINK=$NEXT_PUBLIC_GITHUB_LINK
ENV NEXT_PUBLIC_TG_GROUP_LINK=$NEXT_PUBLIC_TG_GROUP_LINK

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
