// export {default as MainPage} from './MainPage'
// export {default as AboutPage} from './about/ui/AboutPage'
// export {default as ContactsPage} from './contacts/ui/ContactsPage'
// export {default as PortfolioPage} from './PortfolioPage'
// export {default as NotFound} from './not-found/ui/NotFound'